name: vitrine_nova
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^5.6.2

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.4.10

  # Roteamento
  go_router: ^14.2.0
  provider: ^6.1.2

  # Ferramentas de UI e Dispositivo
  image_picker: ^1.2.0
  qr_flutter: ^4.1.0
  uuid: ^4.4.0                 # <-- GARANTA QUE ESTÁ AQUI

    # Ícones
  cupertino_icons: ^1.0.2
  equatable: ^2.0.7
  # Dependencias Para QR, Scanner e impressção/PDF
  qr: ^3.0.1
  image: ^4.0.18
  mobile_scanner: ^3.0.0
  printing: ^5.10.0
  pdf: ^3.10.0
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.5.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true