name: vitrine_nova
description: Vitrine Digital de Moda
publish_to: 'none' # Remove esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_gallery_saver_plus: ^4.0.1

  cupertino_icons: ^1.0.8
  rxdart: ^0.27.7
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  intl: ^0.20.2
  fl_chart: ^1.0.0
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  universal_html: ^2.2.4
  freezed_annotation: ^3.1.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  pinput: ^5.0.1
  crypto: ^3.0.6
  path_provider: ^2.1.5
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true