// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGTAWe6R_P-B9XZfnV6NOn6kYvTvxVPZQ',
    appId: '1:667231698622:web:11ad0bdea76420b94668ef',
    messagingSenderId: '667231698622',
    projectId: 'hooke-loja-pdv-d2e5c',
    authDomain: 'hooke-loja-pdv-d2e5c.firebaseapp.com',
    storageBucket: 'hooke-loja-pdv-d2e5c.firebasestorage.app',
    measurementId: 'G-T3LQBH9CRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEMnZWmk26oIhvH1tUBjN12SCLGs5GOGs',
    appId: '1:667231698622:android:99f915fd5c1dbe714668ef',
    messagingSenderId: '667231698622',
    projectId: 'hooke-loja-pdv-d2e5c',
    storageBucket: 'hooke-loja-pdv-d2e5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf2AxN00MAsEg8_2VslMW6E5XZXBeVGjk',
    appId: '1:667231698622:ios:013e95ad2e5f5f954668ef',
    messagingSenderId: '667231698622',
    projectId: 'hooke-loja-pdv-d2e5c',
    storageBucket: 'hooke-loja-pdv-d2e5c.firebasestorage.app',
    iosBundleId: 'com.example.vitrineNova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf2AxN00MAsEg8_2VslMW6E5XZXBeVGjk',
    appId: '1:667231698622:ios:013e95ad2e5f5f954668ef',
    messagingSenderId: '667231698622',
    projectId: 'hooke-loja-pdv-d2e5c',
    storageBucket: 'hooke-loja-pdv-d2e5c.firebasestorage.app',
    iosBundleId: 'com.example.vitrineNova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGTAWe6R_P-B9XZfnV6NOn6kYvTvxVPZQ',
    appId: '1:667231698622:web:2dbf4401a2247e3b4668ef',
    messagingSenderId: '667231698622',
    projectId: 'hooke-loja-pdv-d2e5c',
    authDomain: 'hooke-loja-pdv-d2e5c.firebaseapp.com',
    storageBucket: 'hooke-loja-pdv-d2e5c.firebasestorage.app',
    measurementId: 'G-ZVM6WC589Z',
  );

}